language: python
python:
  - 2.7
env: GOOGLE_APPENGINE=`pwd`/google_appengine
install:
  - bundle install --quiet --jobs `grep processor /proc/cpuinfo|wc -l`
  - npm install --silent
  - |
    while :; do
      url=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.1$v.zip
      if curl -f -I -s $url >/dev/null; then
        echo use $url
        curl -s -o google_appengine.zip $url && unzip -q google_appengine.zip
        break
      else
        ((v++))
      fi
    done
  - patch -d google_appengine/lib/endpoints-1.0/endpoints -p0 -i ../../../../gae/tap/endpoints.patch
  - pip install --quiet -r requirements.txt
  - pip install --quiet -r requirements-gae.txt
script: make test
