application: gae-tap
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: lxml
  version: latest
- name: pycrypto
  version: latest
- name: webob
  version: latest

inbound_services:
- warmup

builtins:
- deferred: on

default_expiration: 365d

derived_file_type:
- python_precompiled

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon
- url: /sitemap.xml
  static_files: static/sitemap.html
  upload: sitemap.html
  mime_type: text/xml
- url: /static
  static_dir: static
- url: /_ah/stats.*
  script: google.appengine.ext.appstats.ui.app
  login: admin
- url: /_ah/start
  script: utils.app
- url: /_ah/stop
  script: utils.app
- url: /_ah/warmup
  script: utils.app
- url: /_ah/.*
  script: utils.app
  login: admin
- url: /robots.txt
  script: utils.app_static_root
- url: /.*
  script: utils.app

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats
  - name: Response Cache
    url: /_ah/response_cache

skip_files: |
  ^(.*/)?(
  (#.*#)|
  (.*\.coffee)|
  (.*\.haml)|
  (.*\.po)|
  (.*\.pot)|
  (.*\.py[co])|
  (.*\.rb)|
  (.*\.sass)|
  (.*\.sw?)|
  (.*\.yaml)|
  (.*~)|
  (\..*)|
  (gae\/templates\/.*)|
  (htmlcov\/.*)|
  (site-packages\/.+[.](?!py|zip$))|
  (tests\/.*)|
  )$
