application: gae-tap
version: 1
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  max_idle_instances: 1

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: lxml
  version: latest
- name: pycrypto
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest

inbound_services:
- warmup

builtins:
- deferred: on

default_expiration: 365d

derived_file_type:
- python_precompiled

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon
- url: /sitemap.xml
  static_files: static/sitemap.html
  upload: sitemap.html
  mime_type: text/xml
- url: /static
  static_dir: static
- url: /_ah/stats.*
  script: google.appengine.ext.appstats.ui.app
  login: admin
- url: /_ah/(start|stop)
  script: tap.app
- url: /_ah/warmup
  script: warmup.app
- url: /_ah/spi/.*
  script: api.app
- url: /_tap/(generate_sitemap|maintain_response|response_cache)
  script: tap.app
  login: admin
- url: /robots.txt
  script: tap.app_static_root
- url: /.*
  script: tap.app

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats
  - name: Response Cache
    url: /_tap/response_cache

skip_files: |
  ^(.*/)?(
  (#.*#)|
  (.*\.coffee)|
  (.*\.haml)|
  (.*\.mapping)|
  (.*\.po)|
  (.*\.pot)|
  (.*\.py[co])|
  (.*\.rb)|
  (.*\.sass)|
  (.*\.sw?)|
  (.*\.yaml)|
  (.*~)|
  (\..*)|
  (static/version)|
  # if skip raw template files, define `config_JINJA2_FORCE_COMPILED = True` in appengine_config.py for dev_appserver
  #(templates\/.*)|
  (htmlcov\/.*)|
  (site-packages\/.+[.](?!py|zip$))|
  (tests\/.*)|
  )$
